# Generated by PrismFlow — Root Terragrunt configuration
# Do not edit manually. Changes will be overwritten on next deploy.

remote_state {
  backend = "s3"
  config = {
    bucket         = "prismflow-terraform-state"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "terraform-locks"
  }
}

generate "backend" {
  path      = "backend.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
terraform {
  backend "s3" {}
}
EOF
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "aws" {
  region = var.region

  default_tags {
    tags = {
      ManagedBy   = "PrismFlow"
      IaC         = "Terragrunt"
    }
  }
}

variable "region" {
  type    = string
  default = "us-east-1"
}

variable "environment" {
  type = string
}

variable "project_name" {
  type    = string
  default = "prismflow"
}
EOF
}
