# Generated by PrismFlow — Root Terragrunt configuration
# Do not edit manually. Changes will be overwritten on next deploy.
# Deploy: 2026-02-16T00:27:52.868Z

remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    bucket         = "prismflow-terraform-state"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "terraform-locks"

    disable_bucket_update = true
  }
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "aws" {
  region = var.region

  default_tags {
    tags = {
      ManagedBy   = "PrismFlow"
      IaC         = "Terragrunt"
    }
  }
}
EOF
}
