# S3 Bucket: customer-portal-bucket
# Generated by Toyota Data Engineering Portal
# Environment: dev
# Owner: nravikirankumar@gmail.com

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

resource "aws_s3_bucket" "customer_portal_bucket" {
  bucket = "customer-portal-bucket"

  tags = {
    Name        = "customer-portal-bucket"
    Environment = "dev"
    Owner       = "nravikirankumar@gmail.com"
    CostCenter  = "engineering"
    ManagedBy   = "Terraform"
    CreatedBy   = "Toyota-Data-Engineering-Portal"
  }
}

resource "aws_s3_bucket_versioning" "customer_portal_bucket_versioning" {
  bucket = aws_s3_bucket.customer_portal_bucket.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "customer_portal_bucket_encryption" {
  bucket = aws_s3_bucket.customer_portal_bucket.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "true"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "customer_portal_bucket_public_access_block" {
  bucket = aws_s3_bucket.customer_portal_bucket.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}



output "customer_portal_bucket_bucket_name" {
  value       = aws_s3_bucket.customer_portal_bucket.id
  description = "The name of the S3 bucket"
}

output "customer_portal_bucket_bucket_arn" {
  value       = aws_s3_bucket.customer_portal_bucket.arn
  description = "The ARN of the S3 bucket"
}
