# S3 Bucket: final-test-app-dev-logs
# Generated by Toyota Data Engineering Portal
# Environment: dev
# Owner: ravikik@github.com

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

resource "aws_s3_bucket" "final_test_app_dev_logs" {
  bucket = "final-test-app-dev-logs"

  tags = {
    Name        = "final-test-app-dev-logs"
    Environment = "dev"
    Owner       = "ravikik@github.com"
    CostCenter  = "engineering"
    ManagedBy   = "Terraform"
    CreatedBy   = "Toyota-Data-Engineering-Portal"
  }
}

resource "aws_s3_bucket_versioning" "final_test_app_dev_logs_versioning" {
  bucket = aws_s3_bucket.final_test_app_dev_logs.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "final_test_app_dev_logs_encryption" {
  bucket = aws_s3_bucket.final_test_app_dev_logs.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "true"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "final_test_app_dev_logs_public_access_block" {
  bucket = aws_s3_bucket.final_test_app_dev_logs.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}



output "final_test_app_dev_logs_bucket_name" {
  value       = aws_s3_bucket.final_test_app_dev_logs.id
  description = "The name of the S3 bucket"
}

output "final_test_app_dev_logs_bucket_arn" {
  value       = aws_s3_bucket.final_test_app_dev_logs.arn
  description = "The ARN of the S3 bucket"
}
