# DEV environment S3 bucket configuration
# Generated by Toyota Data Engineering Portal
# Application: test-app-demo
# Owner: ravi.kikani@toyota.com
# Generated: 2026-01-02T00:24:48.776Z

include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "../../modules/s3"
}

inputs = {
  bucket_name = "test-app-demo-data-${get_aws_account_id()}"

  enable_versioning = "true"
  enable_encryption = "true"
  sse_algorithm     = "AES256"

  block_public_acls       = "true"
  block_public_policy     = "true"
  ignore_public_acls      = "true"
  restrict_public_buckets = "true"

  enable_lifecycle        = "true"
  transition_days_ia      = "30"
  transition_days_glacier = "90"
  expiration_days         = "365"
  enable_replication      = "false"

  lifecycle_rules = [
    {
      id     = "cleanup-old-versions"
      status = "Enabled"
      expiration = {
        days = 365
      }
    }
  ]

  tags = {
    Application = "test-app-demo"
    Environment = "dev"
    Owner       = "ravi.kikani@toyota.com"
    CostCenter  = "engineering"
    ManagedBy   = "Terraform"
    CreatedBy   = "Toyota-Data-Engineering-Portal"
  }
}
