# DEV environment S3 bucket configuration
# Generated by Toyota Data Engineering Portal
# Application: terragrunt-test-app
# Owner: ravikik@github.com
# Generated: 2026-01-01T01:24:12.177Z

include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "../../modules/s3"
}

inputs = {
  bucket_name = "tg-test-app-dev-data-${get_aws_account_id()}"

  enable_versioning = "true"
  enable_encryption = "true"
  sse_algorithm     = "true"

  block_public_acls       = "true"
  block_public_policy     = "true"
  ignore_public_acls      = "true"
  restrict_public_buckets = "true"

  enable_lifecycle        = "true"
  transition_days_ia      = "30"
  transition_days_glacier = "90"
  expiration_days         = "180"
  enable_replication      = "false"

  lifecycle_rules = [
    {
      id     = "cleanup-old-versions"
      status = "Enabled"
      expiration = {
        days = 180
      }
    }
  ]

  tags = {
    Application = "terragrunt-test-app"
    Environment = "dev"
    Owner       = "ravikik@github.com"
    CostCenter  = "CC-1234"
    ManagedBy   = "Terraform"
    CreatedBy   = "Toyota-Data-Engineering-Portal"
  }
}
